# Exercise on Functions:

# Task-1 Unit Conversion

In [23]:
def convert_length(amount, conversion_type):
    """
    Converts length between meters and feet.
    """
    if conversion_type == 'm_to_ft':
        return amount * 3.28084
    elif conversion_type == 'ft_to_m':
        return amount / 3.28084
    else:
        raise ValueError("Invalid conversion type for length.")

def convert_weight(amount, conversion_type):
    """
    Converts weight between kilograms and pounds.
    """
    if conversion_type == 'kg_to_lbs':
        return amount * 2.20462
    elif conversion_type == 'lbs_to_kg':
        return amount / 2.20462
    else:
        raise ValueError("Invalid conversion type for weight.")

def convert_volume(amount, conversion_type):
    """
    Converts volume between liters and gallons.
    """
    if conversion_type == 'L_to_gal':
        return amount * 0.264172
    elif conversion_type == 'gal_to_L':
        return amount / 0.264172
    else:
        raise ValueError("Invalid conversion type for volume.")

def main():
    """
    Main function to run the unit converter.
    """
    print("Welcome to the Unit Converter!")
    print("Available conversions:")
    print("1. Length: meters to feet, feet to meters")
    print("2. Weight: kilograms to pounds, pounds to kilograms")
    print("3. Volume: liters to gallons, gallons to liters")

    try:
        conversion_category = int(input("Choose the type of conversion (1, 2, or 3): "))
        amount = float(input("Enter the value to be converted: "))

        if conversion_category == 1:
            conversion_type = input("Choose conversion (m_to_ft or ft_to_m): ")
            result = convert_length(amount, conversion_type)
        elif conversion_category == 2:
            conversion_type = input("Choose conversion (kg_to_lbs or lbs_to_kg): ")
            result = convert_weight(amount, conversion_type)
        elif conversion_category == 3:
            conversion_type = input("Choose conversion (L_to_gal or gal_to_L): ")
            result = convert_volume(amount, conversion_type)
        else:
            print("Invalid conversion category selected.")
            return

        print(f"Converted value: {result}")
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()

Welcome to the Unit Converter!
Available conversions:
1. Length: meters to feet, feet to meters
2. Weight: kilograms to pounds, pounds to kilograms
3. Volume: liters to gallons, gallons to liters
Choose the type of conversion (1, 2, or 3): 2
Enter the value to be converted: 50
Choose conversion (kg_to_lbs or lbs_to_kg): kg_to_lbs
Converted value: 110.231


# Task-2 Math Operation on List of Numbers

In [24]:
def get_sum(values):
    """
    Computes the sum of a list of values.
    """
    return sum(values)

def get_average(values):
    """
    Computes the average of a list of values.
    """
    return sum(values) / len(values)

def get_maximum(values):
    """
    Finds the highest number in a list of values.
    """
    return max(values)

def get_minimum(values):
    """
    Finds the lowest number in a list of values.
    """
    return min(values)

def main():
    """
    Main function to execute the mathematical operations program.
    """
    print("Welcome to the Mathematical Operations Program!")
    print("Available operations:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        # Prompt user to select an operation
        operation_choice = int(input("Choose an operation (1, 2, 3, or 4): "))

        # Prompt user to input a list of numbers
        values = list(map(float, input("Enter numbers separated by spaces: ").split()))

        # Ensure the user provided numbers before proceeding
        if not values:
            print("Error: No numbers provided.")
            return

        # Perform the selected mathematical operation
        if operation_choice == 1:
            result = get_sum(values)
            print(f"Sum: {result}")
        elif operation_choice == 2:
            result = get_average(values)
            print(f"Average: {result}")
        elif operation_choice == 3:
            result = get_maximum(values)
            print(f"Maximum: {result}")
        elif operation_choice == 4:
            result = get_minimum(values)
            print(f"Minimum: {result}")
        else:
            print("Invalid operation choice.")
    except ValueError as e:
        # Handle cases where user input is invalid (e.g., non-numeric values)
        print(f"Error: {e}")
    except ZeroDivisionError:
        # Handle division by zero when calculating the average of an empty list
        print("Error: Cannot calculate the average of an empty list.")

# Ensure the script runs only when executed directly, not when imported
if __name__ == "__main__":
    main()

Welcome to the Mathematical Operations Program!
Available operations:
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1, 2, 3, or 4): 3
Enter numbers separated by spaces: 50 30
Maximum: 50.0


# Exercise on List Manipulation:

In [28]:
def extract_every_other(lst):
    """
    Selects every second element from the given list, starting with the first.

    Parameters:
    lst (list): The list to extract elements from.

    Returns:
    list: A new list containing every second element from the original list.
    """
    return lst[::2]  # Uses slicing to pick every alternate element

extract_every_other([1, 2, 3, 4, 5, 6])

[1, 3, 5]

In [29]:
def get_sublist(lst, start, end):
    """
    Extracts a portion of the list from the specified start index to the end index, inclusive.

    Parameters:
    lst (list): The list from which to extract the sublist.
    start (int): The index at which the sublist begins.
    end (int): The index at which the sublist ends.

    Returns:
    list: A new list containing elements from the start index to the end index (inclusive).
    """
    return lst[start:end+1]  # Slicing includes the end index by adding 1

get_sublist([1, 2, 3, 4, 5, 6], 2, 4)

[3, 4, 5]

In [30]:
def reverse_list(lst):
    """
    Returns a reversed version of the given list using slicing.

    Parameters:
    lst (list): The list to be reversed.

    Returns:
    list: A new list with elements in reverse order.
    """
    return lst[::-1]  # Uses slicing with a step of -1 to reverse the list

reverse_list([1, 2, 3, 4, 5])

[5, 4, 3, 2, 1]

In [31]:
def remove_first_last(lst):
    """
    Returns a new list with the first and last elements removed.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A modified list excluding the first and last elements.
    """
    return lst[1:-1]  # Slices the list to exclude the first and last elements

remove_first_last([1, 2, 3, 4, 5])

[2, 3, 4]

In [32]:
def get_first_n(lst, n):
    """
    Returns a new list containing only the first n elements.

    Parameters:
    lst (list): The original list.
    n (int): The number of elements to include.

    Returns:
    list: A list containing the first n elements.
    """
    return lst[:n]  # Extracts elements from the start up to index n

get_first_n([1, 2, 3, 4, 5], 3)

[1, 2, 3]

In [33]:
def get_last_n(lst, n):
    """
    Returns a new list containing only the last n elements.

    Parameters:
    lst (list): The original list.
    n (int): The number of elements to include from the end.

    Returns:
    list: A list containing the last n elements.
    """
    return lst[-n:]  # Extracts the last n elements using slicing

get_last_n([1, 2, 3, 4, 5], 2)

[4, 5]

In [34]:
def reverse_skip(lst):
    """
    Creates a new list by taking every second element from the input list, starting from the second-to-last one and moving backwards.

    Parameters:
    lst (list): The original list to process.

    Returns:
    list: A new list with every other element starting from the second-to-last, going in reverse order.
    """
    return lst[-2::-2]

reverse_skip([1, 2, 3, 4, 5, 6])

[5, 3, 1]

# Exercise on Nested List

In [35]:
def flatten(lst):
    """
    Converts a nested list into a single, flat list.

    Parameters:
    lst (list): The list that may contain other lists within it.

    Returns:
    list: A new list that contains all elements from the nested list, but with no nested structures.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

flatten([[1, 2], [3, [4, 5]], 6])

[1, 2, 3, 4, 5, 6]

In [36]:
def access_nested_element(lst, indices):
    """
    Retrieves an element from a nested list based on a sequence of indices.

    Parameters:
    lst (list): The nested list from which the element will be accessed.
    indices (list): A list of indices specifying the path to the desired element.

    Returns:
    any: The element found at the location defined by the indices.
    """
    for index in indices:
        lst = lst[index]
    return lst

access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2])

6

In [37]:
def sum_nested(lst):
    """
    Computes the total of all numeric values in a nested list.

    Parameters:
    lst (list): The list that may contain nested lists with numbers.

    Returns:
    float: The sum of all numeric elements in the list, including those in nested structures.
    """
    return sum(flatten(lst))

sum_nested([[1, 2], [3, [4, 5]], 6])

21

In [38]:
def remove_element(lst, elem):
    """
    Removes every instance of a specified element from a nested list.

    Parameters:
    lst (list): The list that may contain nested sublists.
    elem (any): The element to be removed.

    Returns:
    list: A new list with all occurrences of the specified element removed.
    """
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

remove_element([[1, 2], [3, 2], [4, 5]], 2)

[[1], [3], [4, 5]]

In [39]:
def find_max(lst):
    """
    Identifies the largest element in a nested list.

    Parameters:
    lst (list): The list that may contain nested sublists.

    Returns:
    float: The largest element found in the list.
    """
    return max(flatten(lst))

find_max([[1, 2], [3, [4, 5]], 6])

6

In [40]:
def count_occurrences(lst, elem):
    """
    Determines the number of times a particular element appears in a nested list.

    Parameters:
    lst (list): The list which may include nested sublists.
    elem (any): The element whose occurrences are to be counted.

    Returns:
    int: The total count of occurrences of the specified element.
    """
    return flatten(lst).count(elem)

count_occurrences([[1, 2], [2, 3], [2, 4]], 2)

3

In [41]:
def deep_flatten(lst):
    """
    Converts a deeply nested list into a single, flat list.

    Parameters:
    lst (list): The list with multiple levels of nesting.

    Returns:
    list: A flattened list containing all the elements from the nested structure.
    """
    return flatten(lst)

deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

[1, 2, 3, 4, 5, 6, 7, 8]

In [42]:
def average_nested(lst):
    """
    Computes the average value of all elements in a nested list.

    Parameters:
    lst (list): The list that may contain nested sublists with numerical elements.

    Returns:
    float: The average of all elements in the flattened list.
    """
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)

average_nested([[1, 2], [3, 4], [5, 6]])

3.5

# Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [43]:
import numpy as np

# 1. Create an uninitialized 2x2 array
empty_array = np.empty((2, 2))
print("Uninitialized 2x2 Array:\n", empty_array)
print("---------------")

# 2. Create a 4x2 array filled with ones
ones_array = np.ones((4, 2))
print("4x2 Array Filled with Ones:\n", ones_array)
print("---------------")

# 3. Generate a 3x3 array where each element is set to 5
fill_value_array = np.full((3, 3), 5)  # Shape: 3x3, Fill Value: 5
print("3x3 Array Filled with 5s:\n", fill_value_array)
print("---------------")

# 4. Create an array of zeros with the same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros Array Matching the Shape of the Given Array:\n", zeros_like_array)
print("---------------")

# 5. Create an array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("Ones Array Matching the Shape of the Given Array:\n", ones_like_array)
print("---------------")

# 6. Convert a Python list into a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("List Converted to NumPy Array:\n", numpy_array)

Uninitialized 2x2 Array:
 [[2.2687441e-316 0.0000000e+000]
 [4.9406565e-324            nan]]
---------------
4x2 Array Filled with Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------
3x3 Array Filled with 5s:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
---------------
Zeros Array Matching the Shape of the Given Array:
 [[0 0]
 [0 0]]
---------------
Ones Array Matching the Shape of the Given Array:
 [[1 1]
 [1 1]]
---------------
List Converted to NumPy Array:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [44]:
# 1. Generate an array of values from 10 to 49
range_array = np.arange(10, 50)
print("Array with Values from 10 to 49:\n", range_array)
print("---------------")

# 2. Create a 3x3 matrix containing values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with Values from 0 to 8:\n", matrix_3x3)
print("---------------")

# 3. Generate a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)
print("---------------")

# 4. Create an array of 30 random numbers and calculate the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array of Size 30:\n", random_array)
print("Mean of Random Array:", mean_value)
print("---------------")

# 5. Generate a 10x10 array of random numbers and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("---------------")

# 6. Create an array of zeros with size 10 and set the 5th element to 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts at 0
print("Zero Array with 5th Element Replaced:\n", zero_array)
print("---------------")

# 7. Reverse the order of elements in an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)
print("---------------")

# 8. Create a 2D array with 1s on the border and 0s inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1s on Border and 0s Inside:\n", border_array)
print("---------------")

# 9. Create an 8x8 array with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

Array with Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------
3x3 Matrix with Values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
Random Array of Size 30:
 [0.82528935 0.3195489  0.23918599 0.56804416 0.90994172 0.75203079
 0.57684563 0.64618268 0.40668607 0.3974881  0.38708827 0.935086
 0.91400105 0.42957147 0.72190843 0.07258931 0.05781931 0.77902722
 0.26421148 0.14865207 0.67856608 0.02051477 0.98812696 0.63241064
 0.00876163 0.46000235 0.54357517 0.37092757 0.18499882 0.1316452 ]
Mean of Random Array: 0.4790242405549907
---------------
10x10 Random Array:
 [[0.35640122 0.23794715 0.89803198 0.4756976  0.29098315 0.08330996
  0.78630847 0.42504984 0.5709294  0.35400671]
 [0.79146538 0.66862825 0.00891532 0.2930531  0.16764152 0.55593998
  0.5297533  0.91201591 0.35728735 0.07570229]
 [0

# Problem - 3: Array Operations:

In [45]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays element-wise
add_result = x + y
print("Addition of x and y:\n", add_result)
print("---------------")

# 2. Subtract the two arrays element-wise
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)
print("---------------")

# 3. Multiply each element of the array by an integer
multiply_result = x * 2
print("Multiplication of x by 2:\n", multiply_result)
print("---------------")

# 4. Calculate the square of each element in the array
square_result = np.square(x)
print("Square of Each Element in x:\n", square_result)
print("---------------")

# 5. Compute the dot product of different arrays
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product of v and w:", dot_vw)
print("Dot Product of x and v:", dot_xv)
print("Dot Product of x and y:\n", dot_xy)
print("---------------")

# 6. Concatenate arrays along rows (axis=0) and along columns (axis=1)
concatenate_rows = np.concatenate((x, y), axis=0)
concatenate_columns = np.vstack((v, w))
print("Concatenate x and y along rows:\n", concatenate_rows)
print("Concatenate v and w along columns:\n", concatenate_columns)
print("---------------")

# 7. Try concatenating x and v (will raise an error due to shape mismatch)
try:
    concatenate_xv = np.concatenate((x, v))
except ValueError as e:
    print("Error:", e)
    print("Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.")

Addition of x and y:
 [[ 6  8]
 [10 13]]
---------------
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
---------------
Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
---------------
Square of Each Element in x:
 [[ 1  4]
 [ 9 25]]
---------------
Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]
---------------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
---------------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.


# Problem - 4: Matrix Operations:

In [46]:
# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I (Identity Matrix)
A_inv = np.linalg.inv(A)  # Inverse of A
identity_check = np.dot(A, A_inv)  # A * A^-1 should give the identity matrix
print("A.A^-1:\n", identity_check)
print("---------------")

# 2. Prove AB != BA (Matrix multiplication is not commutative)
AB = np.dot(A, B)  # Multiply A and B
BA = np.dot(B, A)  # Multiply B and A
print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB != BA?", not np.array_equal(AB, BA))  # Check if AB is not equal to BA
print("---------------")

# 3. Prove (AB)^T = B^T A^T (Transpose of a product of matrices)
AB_transpose = AB.T  # Transpose of AB
B_transpose_A_transpose = np.dot(B.T, A.T)  # B^T * A^T
print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", B_transpose_A_transpose)
print("Is (AB)^T == B^T A^T?", np.array_equal(AB_transpose, B_transpose_A_transpose))
print("---------------")

# Solve the system of linear equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix
B_eq = np.array([-1, -3, 9])  # Right-hand side vector
print("---------------")

# Solve using inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)  # Using matrix inverse
print("Solution using Inverse Method:", X)
print("---------------")

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)  # Using np.linalg.solve to directly solve the system
print("Solution using np.linalg.solve:", X_solve)

A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
---------------
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB != BA? True
---------------
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Is (AB)^T == B^T A^T? True
---------------
---------------
Solution using Inverse Method: [ 2.  1. -2.]
---------------
Solution using np.linalg.solve: [ 2.  1. -2.]


# Experiment: How Fast is Numpy?

In [22]:
import time
import numpy as np

# Function to measure time taken for an operation
def measure_time(func, *args):
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time

# 1. Element-wise Addition
def elementwise_addition_python(list1, list2):
    return [a + b for a, b in zip(list1, list2)]

def elementwise_addition_numpy(array1, array2):
    return array1 + array2

# 2. Element-wise Multiplication
def elementwise_multiplication_python(list1, list2):
    return [a * b for a, b in zip(list1, list2)]

def elementwise_multiplication_numpy(array1, array2):
    return array1 * array2

# 3. Dot Product
def dot_product_python(list1, list2):
    return sum(a * b for a, b in zip(list1, list2))

def dot_product_numpy(array1, array2):
    return np.dot(array1, array2)

# 4. Matrix Multiplication
def matrix_multiplication_python(matrix1, matrix2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
    return result

def matrix_multiplication_numpy(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

# Initialize data
size = 1000000
list1 = list(range(size))
list2 = list(range(size, 2 * size))
array1 = np.arange(size)
array2 = np.arange(size, 2 * size)

matrix_size = 1000
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

# Measure time for each operation
print("1. Element-wise Addition:")
time_python_add = measure_time(elementwise_addition_python, list1, list2)
time_numpy_add = measure_time(elementwise_addition_numpy, array1, array2)
print(f"Python Lists: {time_python_add:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_add:.6f} seconds")

print("\n2. Element-wise Multiplication:")
time_python_mul = measure_time(elementwise_multiplication_python, list1, list2)
time_numpy_mul = measure_time(elementwise_multiplication_numpy, array1, array2)
print(f"Python Lists: {time_python_mul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_mul:.6f} seconds")

print("\n3. Dot Product:")
time_python_dot = measure_time(dot_product_python, list1, list2)
time_numpy_dot = measure_time(dot_product_numpy, array1, array2)
print(f"Python Lists: {time_python_dot:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_dot:.6f} seconds")

print("\n4. Matrix Multiplication:")
time_python_matmul = measure_time(matrix_multiplication_python, matrix1, matrix2)
time_numpy_matmul = measure_time(matrix_multiplication_numpy, np_matrix1, np_matrix2)
print(f"Python Lists: {time_python_matmul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_matmul:.6f} seconds")

1. Element-wise Addition:
Python Lists: 0.167933 seconds
NumPy Arrays: 0.005007 seconds

2. Element-wise Multiplication:
Python Lists: 0.146243 seconds
NumPy Arrays: 0.002354 seconds

3. Dot Product:
Python Lists: 0.162007 seconds
NumPy Arrays: 0.001956 seconds

4. Matrix Multiplication:
Python Lists: 176.345942 seconds
NumPy Arrays: 1.708262 seconds
